version: "3"
services:
  proxy:
    build: ./
    networks:
      - clientA
      - clientB
    ports:
      - "80:80"
    container_name: reverseproxy

networks:
  clientA:
    external:
      name: clienta_default
  clientB:
    external:
      name: clientb_default
